[build]
  command = 'npm run generate'
  functions = 'functions'
  publish = 'dist'

[context.branch-deploy.environment]
  NODE_ENV = 'development'
  SECOND_VAR = 'dev stuff'
  THIRD_VAR = 'more dev stuff'

[context.dev.environment]
  NODE_ENV = 'development'
  SECOND_VAR = 'dev stuff'
  THIRD_VAR = 'more dev stuff'
